py -m pip install pip-review
py -m pip install tqdm
py -m pip install joblib
py -m pip install jupyterlab
py -m pip install numpy
py -m pip install pandas
py -m pip install scipy
py -m pip install math
py -m pip install statistics
py -m pip install scikit-learn
py -m pip install csv
py -m pip install xlrd
py -m pip install XlsxWriter
py -m pip install matplotlib
py -m pip install seaborn
py -m pip install japanize-matplotlib
py -m pip install Pillow
py -m pip install opencv-python
py -m pip install folium
py -m pip install plotly
py -m pip install wordcloud
py -m pip install requests
py -m pip install beautifulsoup4
py -m pip install lxml
py -m pip install selenium
py -m pip install Flask
py -m pip install PyMySQL
py -m pip install PyInstaller
py -m pip install timeit
py -m pip install winsound
py -m pip install sys
py -m pip install tkinter
py -m pip install datetime
py -m pip install dateutil
py -m pip install json
py -m pip install random
py -m pip install os
py -m pip install re
py -m pip install calendar
py -m pip install urllib3
py -m pip install mysqlclient
py -m pip install picture
py -m pip install japanmap
cmd /k